### ISSUE TITLE
Add external viewer link to Ticktack

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#117]
This needs design : 
- [ ] near the vote item :share: button
- [ ] contextual right click

**Comment by mixmix** [comment]
@ticktackim raised the question : 

>  Hey guys, do you think we could implement the Firebase Dynamic Links for the blog/message sharing standard?

@soapdog when you get to this ticket can you have a look into this and quickly decide if this is part of this issue or another one? thanks !

**Comment by soapdog** [comment]
# Internal Share (aka reblog/retweet)

I'm implementing this first because it is easier. I've just added a "retweet" button next to like. Clicking it causes a `share` message to be written to the feed. Right now, I don't have the UI for "quoted retweet", I am doing this afterwards. I do need some icon work. I tried making the icon show with transparency when you haven't retweeted that but it doesn't look good. Some shots below:

![ticktack 2018-04-23 14 18 36](https://user-images.githubusercontent.com/23247/39142505-43d713b8-4701-11e8-89c9-077010f1a85a.png)
_Share icon_

![hyper 2018-04-23 14 12 56](https://user-images.githubusercontent.com/23247/39142422-03a09490-4701-11e8-84f2-0316157aec3f.png)
_shot showing internal share message_

I am trying to get the share counter to behave correctly now by implementing `message.obs.shares`.

**Comment by soapdog** [comment]
Working on external sharing now...

**Comment by soapdog** [comment]
I've also added a lightbox for sharing internally.

![ticktack 2018-04-23 19 24 36](https://user-images.githubusercontent.com/23247/39156319-fdad0d68-472b-11e8-82fe-e214ff270618.png)
_Example of internal reblog with caption entry_

**Comment by ticktackim** [comment]
@soapdog Awesome. Andre, please check the link I send to you guys in Ticktack for the original UI files. There is already the `share` icon design in it.


原始邮件
发件人:Andre Alves Garzianotifications@github.com
收件人:ticktackim/ticktack-workplanticktack-workplan@noreply.github.com
抄送:TickTackmc@ticktack.im; Mentionmention@noreply.github.com
发送时间:2018年4月24日(周二) 06:25
主题:Re: [ticktackim/ticktack-workplan] Add external viewer link toTicktack (#117)


I've also added a lightbox for sharing internally.

 Example of internal reblog with caption entry

**Comment by soapdog** [comment]
This is done pending code review (and little patches)
