### ISSUE TITLE
Notification stats

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#119]
Note this ~~could be~~ **is** more than on issue / feature.

e.g.
- [x] [dashboard showing statistics](https://github.com/ticktackim/ticktack-workplan/issues/130)
- [x] [notification alert for likes on an article](https://github.com/ticktackim/ticktack-workplan/issues/131)

Stats we have access to:
- number followers/ likes / comment / links to article shared (in ssb)

**Comment by mixmix** [comment]
![selection_558](https://user-images.githubusercontent.com/2665886/38178144-5d23f4be-3660-11e8-9218-f40d054fbb16.jpg)

here's the sort of notifications Medium have. I was expecting some state page like this with the design @ticktackim

**Comment by soapdog** [comment]
@ticktackim hey Marco, I've seen the UI design you shared with us and I just want to clarify that what I have always thought about a notifications/stats page is something similar to the analytics displayed above where the user can, at a glance, have an understanding of the "big picture" of his social network outreach and impact.

I think this is the kind of thing I would prefer that we implement instead of the design shown on that sketch-like web app. What do you think?

**Comment by ticktackim** [comment]
@mixmix @soapdog  Yeah, if you agree above is not complicated to implement, I will have designer improved the ui like that. But one more thing is we still need to put an entrance to let the author reply to the comments on this page, correct? At this moment, the author needs to click to the subject blogs in order to reply to a specific comment. This is a hassle.

**Comment by ticktackim** [comment]
![default](https://user-images.githubusercontent.com/30351648/38319461-640b3566-3864-11e8-9ebd-a8c37e89735e.png)

@mixmix @soapdog  Hey guys, please see above improve ui designs for the notification page. The UX process will be `click the notification icon` => `prompt up the floating window` => `click the Stats` => `prompt to the stats page`.  `Stats Page` is completely based on Medium alike. Users can also `click the relative blog links to reply to the comments directly. 

Please confirm by return if this is better. So I will have designer finish the sketch files next week.

**Comment by mixmix** [comment]
hey @ticktackim we talked about this on our call just now. Page 2 (the graphs) looks clear. 
Page 3 + , we want to recommend that we just use the blog show page ... as in each blog already has this comments section built underneath.

For page 1, this looks good. Making a good dropdown menu like that will take some care. I think I'd also like to make a feature where in the Settings page you can modify what shows up in this (e.g. as a user I want to disable all the like messages notifications because they take up a lot of space and make it hard to see the comments. But other users may love that)

**Comment by mixmix** [comment]
I'm going to start on Page 2 this week

**Comment by ticktackim** [comment]
@mixmix Yeah, your suggestion for the setting page is awesome.

发自我的 iPhone

**Comment by mixmix** [comment]
Note this is a large job - I've split this out into two issues so they're more _bite sized pieces_ 
#130 #131
