### ISSUE TITLE
Initial page sentence change

### ISSUE THREAD

**Issue by ticktackim** [ticktackim/ticktack-workplan#124]
@mixmix  Please change the initial page sentence to 

" A decentralized social network enable people to share knowledge and exchange value."

**Comment by mixmix** [comment]
Which sentence do you want to replace : 
1. `A new era social network for people who have faith in a decentralized world that values openness, equality, and freedom`
2. `Connecting the Unconnected Reconstructing a trusty social network

**Comment by mixmix** [comment]
@ticktackim I find your attention to what we value something I really respect. I think a challenge is that there are lots of English speaking companies who have nice sayings or company slogans, but they don't really mean them. That means that if a person doesn't know you, they will likely read this as just another company lying (this is a sad state for the world to be in).

So I think this opening language needs a lot of care, so that people understand the importance and care we have. I have an idea for this : **How about we ask the people of Scuttlebutt to help us come up with some language which feels really strong and true to our values?**
I think the advantage of this is that it would be a chance to discuss with people what the dream with Ticktack is, and to get some great minds to support us find great language.

If you're open to this idea I'd love to start the conversation and then for us all to be a part.

**Comment by ticktackim** [comment]
@mixmix I plan to replace the first sentence as it seems too big word for users. But your suggestion is quite good. Let's see how the community will revert to you.

**Comment by mixmix** [comment]
Posted this up on scuttlebutt `%8HLT/Sq9e9SZoIdO9taB2EgiY6L4N2M1IsqpYUzsgtE=.sha256`

**Comment by mixmix** [comment]
I've merged a change which shows a range of different values that were expressed by the community. It choses one at random on startup from : 
   1. A social network that values openness, equality, and freedom.
   2. A new social network for people seeking an equitable world that values the value people create and successfully balances freedom, solidarity, privacy, and openness.
   3. Let's do it right this time. A Web 3.0 social network, connecting the next billion with a decentralized platform built for openness, freedom, and equality.
   4. An open, equal and free social network.

I've changed the "slogan" to : 
  - slogan: 'Ticktack: blogging for the decentralized era'


We can easily tune these or add to them as required.
example of what it looks like:

![image](https://user-images.githubusercontent.com/2665886/38589519-83c62346-3d7f-11e8-8ea1-62c16aba7198.png)

**Comment by ticktackim** [comment]
@mixmix That's awesome. #2 and #3 are both good. And #2 seems better to express our community values. But why I didn't see these threads on my ticktack client?

For the slogan, I'd like to stick to "Connecting to the unconnected, Rebuilding a trusty social network". Since slogan will point the direction of where we are heading to, it needs to be broad and utmost. Defining just as a blogging platform is too constricted.
