### ISSUE TITLE
stats page cuts off left or right side unless full screen

### ISSUE THREAD

**Issue by masukomi** [ticktackim/ticktack-workplan#158]
either it cuts off the right side or the left side unless you make the window. I feel like there's nothing about this design that wouldn't be achievable with responsive css 

![ticktack](https://user-images.githubusercontent.com/2829/40895637-985fbcee-677e-11e8-8d4d-42d01517663f.png)

**Comment by ticktackim** [comment]
@masukomi I think it is because you Zoom + a bit more. Would you please adjust the Zoom -+ on the setting page to try it again?

**Comment by mixmix** [comment]
we can have a quick look at how this is styled and what's not causing it to shrink some.
Once challenge is that I often want to set a `min-width` for things while they're loading so that the page doesn't magically change size as content comes in - this is really jarring.

I think we could set something like `min-width: 70vw` (70% of the view window) or `calc(100vw - 4rem)` or whatever that sidebar width is., then have the whole thing be allowed to "grow" up to a certain max.
I think css-grid might help with this

**Comment by mixmix** [comment]
@masukomi I've looked into this. It is responsive, but the canvas (what the graph is made with) sets it's size when this page is loaded.

If you have a smalled browser window and then go to this page it's fine: 

![image](https://user-images.githubusercontent.com/2665886/41951861-2a3b6c08-7a21-11e8-922f-7061137345f1.png)

The minimum width form the app window that works with this design is 865px.

Given the page behaves well, _except_ when you have this exact page open and then resize the app window, I'm going to close this issue for now - I could figure out how to get the graph to redraw, but _I think_ this is an edge case.
Let me know if you think I'm wrong

**Comment by masukomi** [comment]
sorry about the delay.... 
> Let me know if you think I'm wrong

no. that's probably the right call. the amount of work required to make this work as desired just isn't worth the payoff... at least not at this point in time. switching to a non-canvas based graph package (either SVG or CSS) would probably address it but, again not worth prioritizing at the moment.
